global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'test'
    file_sd_configs:
      - files:
          - /tmp/prometheus/targets/target_*.json